addSbtPlugin("org.scalameta"             % "sbt-scalafmt" % "2.4.0")
addSbtPlugin("com.dwijnand"              % "sbt-dynver"   % "4.0.0")
addSbtPlugin("de.heikoseeberger"         % "sbt-header"   % "5.6.0")
addSbtPlugin("io.github.davidgregory084" % "sbt-tpolecat" % "0.1.11")
addSbtPlugin("com.jsuereth"              % "sbt-pgp"      % "2.0.1")
addSbtPlugin("org.xerial.sbt"            % "sbt-sonatype" % "3.9.2")
