addSbtPlugin("org.scalameta"             % "sbt-scalafmt" % "2.3.2")
addSbtPlugin("com.dwijnand"              % "sbt-dynver"   % "4.0.0")
addSbtPlugin("de.heikoseeberger"         % "sbt-header"   % "5.4.0")
addSbtPlugin("io.github.davidgregory084" % "sbt-tpolecat" % "0.1.11")
addSbtPlugin("com.jsuereth"              % "sbt-pgp"      % "2.0.0-M2")
addSbtPlugin("org.xerial.sbt"            % "sbt-sonatype" % "3.8.1")
